import { useEffect, useMemo, useState } from 'react';
const commands=[
 ['Go to Hero','home hero top intro','hero'],['Go to Projects','projects work portfolio','projects'],['Go to Hobbies','hobbies drawings art','hobbies'],['Go to Timeline','timeline milestones roadmap','timeline'],
 ['Show Archive Timeline','archive timeline project','timeline:archive'],['Show AASTU-SOCIAL Timeline','aastu social timeline project','timeline:aastu-social'],['Show WIFI-Crasher Timeline','wifi crasher timeline project','timeline:wifi-crasher'],
 ['Go to Contact','footer contact socials','footer'],['Open GitHub','github profile repo','github'],['Open Telegram','telegram chat message','telegram'],['Email Me','gmail mail email contact','email'],['Download Resume','resume cv pdf download','resume'],['Toggle Recruiter Mode','recruiter mode clean view','recruiter']
];
export default function CommandPalette({open,onClose,onProject,onRecruiter,onResume}){
 const [query,setQuery]=useState(''),[active,setActive]=useState(0);
 const filtered=useMemo(()=>commands.filter(c=>`${c[0]} ${c[1]}`.toLowerCase().includes(query.trim().toLowerCase())),[query]);
 useEffect(()=>{if(!open)return;setQuery('');setActive(0);const key=e=>{if(e.key==='Escape')onClose();else if(e.key==='ArrowDown'){e.preventDefault();setActive(i=>filtered.length?(i+1)%filtered.length:0)}else if(e.key==='ArrowUp'){e.preventDefault();setActive(i=>filtered.length?(i-1+filtered.length)%filtered.length:0)}else if(e.key==='Enter'){e.preventDefault();run(filtered[active])}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key)},[open,filtered,active]);
 const run=c=>{if(!c)return;onClose();const a=c[2];if(a.startsWith('timeline:'))onProject(a.split(':')[1]);else if(a==='timeline')scroll('timeline');else if(a==='github')window.open('https://github.com/squidward404','_blank','noopener,noreferrer');else if(a==='telegram')window.open('https://t.me/A_t_o_m_ic','_blank','noopener,noreferrer');else if(a==='email')window.location.href='mailto:befikirshimelis20@gmail.com';else if(a==='resume')onResume();else if(a==='recruiter')onRecruiter();else scroll(a)};
 const scroll=id=>document.getElementById(id)?.scrollIntoView({behavior:'smooth'});
 if(!open)return null;
 return <div className="command-palette-overlay" onClick={e=>e.target===e.currentTarget&&onClose()}><div aria-label="Command palette" aria-modal="true" className="command-palette" role="dialog"><input autoFocus className="command-input" value={query} onChange={e=>{setQuery(e.target.value);setActive(0)}} placeholder="Type a command..." autoComplete="off"/><ul className="command-list">{filtered.length?filtered.map((c,i)=><li key={c[0]}><button className={`command-item ${i===active?'active':''}`} onMouseEnter={()=>setActive(i)} onClick={()=>run(c)}>{c[0]}</button></li>):<li className="command-empty">No matching commands</li>}</ul><p className="command-hint">Ctrl/Cmd + K to open • ↑ ↓ to navigate • Enter to run • Esc to close</p></div></div>
}
